version: "3.9"

services:
  sql2022:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql2022
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - ./backups:/var/opt/mssql/backups    # tu lądują .bak z Google Drive
      - sql2022_data:/var/opt/mssql/data    # dane
    restart: unless-stopped

volumes:
  sql2022_data:
